name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
   types: [contentful.deploy]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
        GATSBY_ACCESS_TOKEN: ${{secrets.GATSBY_ACCESS_TOKEN}}
        GATSBY_SPACE_ID: ${{secrets.GATSBY_SPACE_ID}}
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm i
      
    - name: User fix
      run: |
        git config user.name github-actions
        git config user.email github-actions@github-private
        git remote set-url origin git@github-private:spgarn/frogsong.git
      
    - name: deploy project
      run: npm run deploy
      
